### PR TITLE
Enhance textarea

### PR DESCRIPTION
**Pull request by iitzIrFan**
**#53 Enhance TextArea component accessibility**    

- Proper labeling with the textarea element.
- Added correct aria attributes.
- To prevent conflicts between multiple text input components I had added unique id's.
- Other required changes as per the report.

This was done to Enhance the accessibility of TextArea component as Lighthouse tool & hooping it would be merged in main branch of the project.

### CODE REVIEW

**Comment by harshmangalam** [comment]
Thanks

**Comment by iitzIrFan** [comment]
Your welcome.

**Comment by harshmangalam** [comment]
Hi @iitzIrFan ,

Thank you so much for contributing to qwik-x during Hacktoberfest! Your efforts are truly appreciated, and we’d love to give you kudos and a shout-out for your amazing work.

If you're comfortable, please feel free to share your social media handles like linkedin, twitter,etc... so we can tag you in our appreciation posts and spread the word about your contributions!

Looking forward to seeing you in the community. Thanks again for being awesome!

Best,
Harsh Mangalam
Maintainer qwik-x

**Comment by iitzIrFan** [comment]
@harshmangalam 

Thanks for the appreciation! It was great contributing to qwik-x during Hacktoberfest. Here’s my LinkedIn handle :- www.linkedin.com/in/irfan-shaikh-8b5b94259. I’d be grateful if you could recommend me on LinkedIn for my work on the project.

Looking forward to staying connected!

Best,
Irfan Shaikh

**Pull request merged**
